import type { Metadata } from "next";
import { Geist, Geist_Mono, Micro_5 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const micro5 = Micro_5({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-micro5",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${micro5.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
